name: Backend Testing

on:

  push:
    branches: [ backend ]
  pull_request:
    branches: [ backend ]
    
  workflow_dispatch:
  
jobs:
 build:

    runs-on: windows-latest

    steps:
    
      - name: Checkout master branch from Github
        uses: actions/checkout@v2
        
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          
      - name: Set up the packages
        run: javac -classpath lib/* -d ./src/Rest/*.java
        
      - name: Running the code
        run: java -cp lib/*; org.testng.TestNG testng.xml
         
